export interface CountryDatum {
  name: string;
}

export const COUNTRY_DATA: Record<string, CountryDatum> = {
  af: { name: "Afghanistan" },
  ax: { name: "Åland Islands" },
  al: { name: "Albania" },
  dz: { name: "Algeria" },
  as: { name: "American Samoa" },
  ad: { name: "Andorra" },
  ao: { name: "Angola" },
  ai: { name: "Anguilla" },
  aq: { name: "Antarctica" },
  ag: { name: "Antigua and Barbuda" },
  ar: { name: "Argentina" },
  am: { name: "Armenia" },
  aw: { name: "Aruba" },
  au: { name: "Australia" },
  at: { name: "Austria" },
  az: { name: "Azerbaijan" },
  bs: { name: "Bahamas" },
  bh: { name: "Bahrain" },
  bd: { name: "Bangladesh" },
  bb: { name: "Barbados" },
  by: { name: "Belarus" },
  be: { name: "Belgium" },
  bz: { name: "Belize" },
  bj: { name: "Benin" },
  bm: { name: "Bermuda" },
  bt: { name: "Bhutan" },
  bo: { name: "Bolivia" },
  bq: { name: "Caribbean Netherlands" },
  ba: { name: "Bosnia and Herzegovina" },
  bw: { name: "Botswana" },
  bv: { name: "Bouvet Island" },
  br: { name: "Brazil" },
  io: { name: "British Indian Ocean Territory" },
  bn: { name: "Brunei Darussalam" },
  bg: { name: "Bulgaria" },
  bf: { name: "Burkina Faso" },
  bi: { name: "Burundi" },
  cv: { name: "Cabo Verde" },
  kh: { name: "Cambodia" },
  cm: { name: "Cameroon" },
  ca: { name: "Canada" },
  ky: { name: "Cayman Islands" },
  cf: { name: "Central African Republic" },
  td: { name: "Chad" },
  cl: { name: "Chile" },
  cn: { name: "China" },
  cx: { name: "Christmas Island" },
  cc: { name: "Cocos (Keeling) Islands" },
  co: { name: "Colombia" },
  km: { name: "Comoros" },
  cg: { name: "Congo" },
  cd: { name: "Democratic Republic of the Congo" },
  ck: { name: "Cook Islands" },
  cr: { name: "Costa Rica" },
  ci: { name: "Côte d'Ivoire" },
  hr: { name: "Croatia" },
  cu: { name: "Cuba" },
  cw: { name: "Curaçao" },
  cy: { name: "Cyprus" },
  cz: { name: "Czechia" },
  dk: { name: "Denmark" },
  dj: { name: "Djibouti" },
  dm: { name: "Dominica" },
  do: { name: "Dominican Republic" },
  ec: { name: "Ecuador" },
  eg: { name: "Egypt" },
  sv: { name: "El Salvador" },
  gq: { name: "Equatorial Guinea" },
  er: { name: "Eritrea" },
  ee: { name: "Estonia" },
  sz: { name: "Eswatini" },
  et: { name: "Ethiopia" },
  fk: { name: "Falkland Islands" },
  fo: { name: "Faroe Islands" },
  fj: { name: "Fiji" },
  fi: { name: "Finland" },
  fr: { name: "France" },
  gf: { name: "French Guiana" },
  pf: { name: "French Polynesia" },
  tf: { name: "French Southern Territories" },
  ga: { name: "Gabon" },
  gm: { name: "Gambia" },
  ge: { name: "Georgia" },
  de: { name: "Germany" },
  gh: { name: "Ghana" },
  gi: { name: "Gibraltar" },
  gr: { name: "Greece" },
  gl: { name: "Greenland" },
  gd: { name: "Grenada" },
  gp: { name: "Guadeloupe" },
  gu: { name: "Guam" },
  gt: { name: "Guatemala" },
  gg: { name: "Guernsey" },
  gn: { name: "Guinea" },
  gw: { name: "Guinea-Bissau" },
  gy: { name: "Guyana" },
  ht: { name: "Haiti" },
  hm: { name: "Heard Island and McDonald Islands" },
  va: { name: "Holy See" },
  hn: { name: "Honduras" },
  hk: { name: "Hong Kong" },
  hu: { name: "Hungary" },
  is: { name: "Iceland" },
  in: { name: "India" },
  id: { name: "Indonesia" },
  ir: { name: "Iran" },
  iq: { name: "Iraq" },
  ie: { name: "Ireland" },
  im: { name: "Isle of Man" },
  il: { name: "Israel" },
  it: { name: "Italy" },
  jm: { name: "Jamaica" },
  jp: { name: "Japan" },
  je: { name: "Jersey" },
  jo: { name: "Jordan" },
  kz: { name: "Kazakhstan" },
  ke: { name: "Kenya" },
  ki: { name: "Kiribati" },
  kp: { name: "North Korea" },
  kr: { name: "South Korea" },
  kw: { name: "Kuwait" },
  kg: { name: "Kyrgyzstan" },
  la: { name: "Laos" },
  lv: { name: "Latvia" },
  lb: { name: "Lebanon" },
  ls: { name: "Lesotho" },
  lr: { name: "Liberia" },
  ly: { name: "Libya" },
  li: { name: "Liechtenstein" },
  lt: { name: "Lithuania" },
  lu: { name: "Luxembourg" },
  mo: { name: "Macau" },
  mg: { name: "Madagascar" },
  mw: { name: "Malawi" },
  my: { name: "Malaysia" },
  mv: { name: "Maldives" },
  ml: { name: "Mali" },
  mt: { name: "Malta" },
  mh: { name: "Marshall Islands" },
  mq: { name: "Martinique" },
  mr: { name: "Mauritania" },
  mu: { name: "Mauritius" },
  yt: { name: "Mayotte" },
  mx: { name: "Mexico" },
  fm: { name: "Federated States of Micronesia" },
  md: { name: "Moldova" },
  mc: { name: "Monaco" },
  mn: { name: "Mongolia" },
  me: { name: "Montenegro" },
  ms: { name: "Montserrat" },
  ma: { name: "Morocco" },
  mz: { name: "Mozambique" },
  mm: { name: "Myanmar" },
  na: { name: "Namibia" },
  nr: { name: "Nauru" },
  np: { name: "Nepal" },
  nl: { name: "Netherlands" },
  nc: { name: "New Caledonia" },
  nz: { name: "New Zealand" },
  ni: { name: "Nicaragua" },
  ne: { name: "Niger" },
  ng: { name: "Nigeria" },
  nu: { name: "Niue" },
  nf: { name: "Norfolk Island" },
  mk: { name: "North Macedonia" },
  mp: { name: "Northern Mariana Islands" },
  no: { name: "Norway" },
  om: { name: "Oman" },
  pk: { name: "Pakistan" },
  pw: { name: "Palau" },
  ps: { name: "Palestine" },
  pa: { name: "Panama" },
  pg: { name: "Papua New Guinea" },
  py: { name: "Paraguay" },
  pe: { name: "Peru" },
  ph: { name: "Philippines" },
  pn: { name: "Pitcairn" },
  pl: { name: "Poland" },
  pt: { name: "Portugal" },
  pr: { name: "Puerto Rico" },
  qa: { name: "Qatar" },
  re: { name: "Réunion" },
  ro: { name: "Romania" },
  ru: { name: "Russian Federation" },
  rw: { name: "Rwanda" },
  bl: { name: "Saint Barthélemy" },
  sh: { name: "Saint Helena" },
  kn: { name: "Saint Kitts and Nevis" },
  lc: { name: "Saint Lucia" },
  mf: { name: "Saint Martin (French part)" },
  pm: { name: "Saint Pierre and Miquelon" },
  vc: { name: "Saint Vincent and the Grenadines" },
  ws: { name: "Samoa" },
  sm: { name: "San Marino" },
  st: { name: "Sao Tome and Principe" },
  sa: { name: "Saudi Arabia" },
  sn: { name: "Senegal" },
  rs: { name: "Serbia" },
  sc: { name: "Seychelles" },
  sl: { name: "Sierra Leone" },
  sg: { name: "Singapore" },
  sx: { name: "Sint Maarten (Dutch part)" },
  sk: { name: "Slovakia" },
  si: { name: "Slovenia" },
  sb: { name: "Solomon Islands" },
  so: { name: "Somalia" },
  za: { name: "South Africa" },
  gs: { name: "South Georgia and the South Sandwich Islands" },
  ss: { name: "South Sudan" },
  es: { name: "Spain" },
  lk: { name: "Sri Lanka" },
  sd: { name: "Sudan" },
  sr: { name: "Suriname" },
  sj: { name: "Svalbard and Jan Mayen" },
  se: { name: "Sweden" },
  ch: { name: "Switzerland" },
  sy: { name: "Syrian Arab Republic" },
  tw: { name: "Taiwan" },
  tj: { name: "Tajikistan" },
  tz: { name: "Tanzania" },
  th: { name: "Thailand" },
  tl: { name: "Timor-Leste" },
  tg: { name: "Togo" },
  tk: { name: "Tokelau" },
  to: { name: "Tonga" },
  tt: { name: "Trinidad and Tobago" },
  tn: { name: "Tunisia" },
  tr: { name: "Turkey" },
  tm: { name: "Turkmenistan" },
  tc: { name: "Turks and Caicos Islands" },
  tv: { name: "Tuvalu" },
  ug: { name: "Uganda" },
  ua: { name: "Ukraine" },
  ae: { name: "United Arab Emirates" },
  gb: { name: "United Kingdom" },
  us: { name: "United States" },
  um: { name: "United States Minor Outlying Islands" },
  uy: { name: "Uruguay" },
  uz: { name: "Uzbekistan" },
  vu: { name: "Vanuatu" },
  ve: { name: "Venezuela" },
  vn: { name: "Vietnam" },
  vg: { name: "British Virgin Islands" },
  vi: { name: "US Virgin Islands" },
  wf: { name: "Wallis and Futuna" },
  eh: { name: "Western Sahara" },
  ye: { name: "Yemen" },
  zm: { name: "Zambia" },
  zw: { name: "Zimbabwe" },
};
